# Remain backwards compatible with Python 2.6 for now.

import subprocess
import shutil


def run(argv):
    subprocess.check_call(argv)


def run_discard_err(argv):
    with open("/dev/null", "w") as devnull:
        subprocess.call(argv, stderr=devnull)


def concat(target, source, env):
    dst = str(target[0])
    srcs = sorted(str(s) for s in source)
    run_discard_err(["chmod", "0600", dst])
    with open(dst, "w") as fdst:
        for src in srcs:
            with open(src) as fsrc:
                shutil.copyfileobj(fsrc, fdst)
    run(["chmod", "0400", dst])


Import("env")
env.Command("config", Glob("config.d/*"), concat)
env.Command("known_hosts", Glob("known_hosts.d/*"), concat)
