import subprocess
import shutil

from subprocess import DEVNULL


def concat(target, source, env):
    dst = str(target[0])
    srcs = sorted(str(s) for s in source)
    subprocess.run(["chmod", "0600", dst], stderr=DEVNULL, check=False)
    with open(dst, "w") as fdst:
        for src in srcs:
            with open(src) as fsrc:
                shutil.copyfileobj(fsrc, fdst)
    subprocess.run(["chmod", "0400", dst], check=True)


Import("env")
env.Command("config", Glob("config.d/*"), concat)
env.Command("known_hosts", Glob("known_hosts.d/*"), concat)
